### ISSUE TITLE
请问里面import的MySQLdb是MySQL-python里面的吗？

### ISSUE THREAD

**Issue by cedricporter** [scutwukai/smartpool#1]
请问里面import的MySQLdb是 https://pypi.python.org/pypi/MySQL-python/1.2.5 吗？

**Comment by scutwukai** [comment]
应该是的，主要就是用到了 connection 对象，还有一些常量，只要接口一致就行，不一定用特定的包

**Comment by cedricporter** [comment]
是不是有其他的MySQL库能够配合gevent使用呢？

**Comment by scutwukai** [comment]
gevent 要访问 Mysql，需要使用 ultramysql + umysqldb

ultramysql 是数据库驱动， umysqldb 是对 ultramysql 的包装

**Comment by cedricporter** [comment]
锴哥威武

**Comment by zheng-ji** [comment]
路过点赞
